export const API = "API"
export const SET_USER_INFO = "SET_USER_INFO"
export const RESET_USER_INFO = "RESET_USER_INFO"
export const GET_ACCOUNTS = "GET_ACCOUNTS"
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const GET_BALANCES = "GET_BALANCES"
export const GET_OWNERS = "GET_OWNERS"